### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/

### ISSUE THREAD

**Issue by vikramhn** [Azure-Samples/angular-cosmosdb#11]
followed your steps - as described here -> https://github.com/Azure-Samples/angular-cosmosdb/
getting an error when I browse - http://localhost:3000
API running on localhost:3000
Mongoose: heroes.ensureIndex({ id: 1 }, { unique: true, background: true })
Error: ENOENT: no such file or directory, stat '/Users/vikram/dev/angular/cosmosmaster/angular-cosmosdb/dist/index.html'
    at Error (native)

**Comment by johnpapa** [comment]
Hi, thanks for opening this. Can you verify that you ran the `nb build` step and that it created a folder `/dist` with the `index.html` file in it?

**Comment by vikramhn** [comment]
I ran the ng build. The dist folder was created but does not have the index.html. It is under publicweb though.

Attached is the screen shot.

________________________________

**Comment by anotherrohit** [comment]
@johnpapa  same issue here. dist was created but index.html absent. Any clues on what went wrong here.Also saw this after node src/server/index.js 
(node:72784) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: Authentication Failed
(node:72784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: ENOENT: no such file or directory, stat '/Users/myid/Downloads/angular-cosmosdb/publicweb/index.html'

but az login was successful.

**Comment by johnpapa** [comment]
@anotherrohit  

the express server files are placed in `/dist` and express serves the files in `/dist/publicweb` (the angular files).

`Auth failed` means your mongo connection could not be made properly. be sure to connect to a valid mongo or cosmos db database.

**Comment by johnpapa** [comment]
I just made a change to the master branch's mongo connection string settings and updated the readme to reflect it. Please try to pull the latest and update your connection string settings.

**Comment by anotherrohit** [comment]
Got it! the authentication works now, but still see the error on the page
Error: ENOENT: no such file or directory, stat '/Users/uid/Downloads/angular-cosmosdb/publicweb/index.html

note the dist is missing in the error,seems the path has not been set to read dist?Where can i change this?

**Comment by johnpapa** [comment]
awesome, thanks

**Comment by vikramhn** [comment]
That's correct, below command fixed the issue
ng build --output-path=publicweb
